### ISSUE TITLE
AttributeError: module 'openal.al' has no attribute 'ALint'

### ISSUE THREAD

**Issue by Helawe** [cruxicheiros/AudioEnvironments#2]
I got this error while i was trying to run 'python forest.py'

Traceback (most recent call last):
  File "forest.py", line 4, in <module>
    from openal.audio import SoundSink, SoundSource, SoundListener
  File "D:\Python\lib\site-packages\openal\audio.py", line 111, in <module>
    al.AL_FREQUENCY: (al.ALint, al.alBufferi, al.alGetBufferi),
AttributeError: module 'openal.al' has no attribute 'ALint'

please help 😞 😢 🙏

**Comment by cruxicheiros** [comment]
Hi Helawe: 
I don't recommend using AudioEnvironments: I wrote it for a demo, it doesn't work that well, and I haven't touched it in a very long time.
If you let me know what you are trying to use it for, I can help you find an alternative.
Clark

**Comment by Helawe** [comment]
thanks buddy for your quick reply...
I was trying to generate a 3D format of an audio (.wav file) by giving a the required parameters.
my project is 'an assistant system for visually impaired or blind people', my system will grab a video and detect the potential obstacles from the environment, and based on the spacial location of the obstacles, i need to generate a sound to alert the blind or VI person... 

wish to hear something from you, and thanks for ur time pal...

**Comment by cruxicheiros** [comment]
Okay. I'm assuming that this is for a coursework project/school assignment of some form and not for a practical implementation that someone is actually going to use. For that, ["The vOICe"](https://www.seeingwithsound.com/) already exists (and you may be able to get some inspiration from it).

I can let you know what I learned from my personal projects with 3D audio, and hopefully the information will help you.

What I recommend, after a massive amount of trial and error, is using an audio manipulation library like [PyDub](https://github.com/jiaaro/pydub) (I love PyDub--it's incredible) and writing your own solution. You will definitely get further than if you use someone else's solution (because there aren't very many, and they very often don't work) because it gives you the ability to solve issues when you run into them.

So, how do you turn 2D audio into 3D audio? Well, this is actually just an approximation of 3D audio. True 3D audio is not really doable without the use of HRTFs (head-related transfer functions) which are difficult to implement and (as I will get into) is probably not the solution you want anyway.

So, there are three main issues involved in 3D audio. They are:
- Making sound come from the right position around the listener from right to left, i.e. if a sound comes from your left side it should sound like it is coming from your left side
- Making things sound like they come from an appropriate distance away, i.e. something further away should sound quieter than something closer
- Making things sound like they come from behind the listener.

**Making sound come from the right position around the listener from right to left is very easy.** You can use trigonometry to work out where an object is in relation to the listener, then pan the sound to the appropriate amount. The second two are more hard.

**Making things sound like they come from an appropriate distance away** is a lot harder. This is because the amount a sound gets quieter by doesn't have a linear relationship with the amount of distance away. Decibel drop is actually logarithmic and can be approximated with the [Inverse Square Law](http://hyperphysics.phy-astr.gsu.edu/hbase/Acoustic/isprob2.html). However, this is only an approximation and is not perfect. As well, assuming that you _can_ tell distance away with your camera setup, telling someone how far away something is via **volume** might not be what you want to do. The person using your device might be in a noisy environment, or might need to hear about a rapidly approaching object--in which case, they should know about it while it is still far away.

**Making things sound like they come from behind the listener** is a very hard problem and if it's within the scope of your project, I don't recommend attempting to manipulate the sound to make it sound like it's behind the listener. It is possible to create this effect by inverting the phase of one side of the audio, but **this only really works when the sound source is directly behind the listener.** Most of the time, you won't get this situation, and it will be very difficult if not impossible for a listener to tell if the sound is behind or in front of them. 

The alternate solutions to the second problems, which I feel would serve you better, are changing different aspects of the audio alert. For example, changing pitch based on distance away, or playing a tonally different alert for objects that are behind the listener.

I hope this helps you, and if you remember, let me know how this turns out!

**Comment by Helawe** [comment]
Thank you so much buddy, i found your comment as a great tutor 😉 
i'll try it and let you know my progress... thank you again 🙏
